dist:
  name: otelcol-cloudflaregraphql
  description: OpenTelemetry Collector with Cloudflare receiver
  output_path: ./dist
  otelcol_version: "0.148.0"

receivers:
  - gomod: github.com/m1keru/cloudflaregraphqlreceiver v0.148.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.148.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.148.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.148.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.148.0
